name: PowerShell Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install PSScriptAnalyzer
      shell: pwsh
      run: |
        Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force -Confirm:$false

    - name: Run lint script
      shell: pwsh
      run: |
        pwsh -NoProfile -ExecutionPolicy Bypass -File .\lint.ps1
